# Generated by Django 4.0.2 on 2022-03-07 18:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
